### ISSUE TITLE
some feedback

### ISSUE THREAD

**Issue by xiaopeng163** [yumemor/hexo-theme-primer#1]
用了一下，几点反馈。
1. 中英文切换 

最好能配置中英文，这样在英文条件下hexo generate出来的，像“文章目录”，“继续阅读”可以自动匹配成英文
1. 留言版

配置了disqus貌似不管用？
1. 首页的大标题怎么配置Stay Hungry. Stay Foolish

我的配置

``` yml
# Header
menu:
    Home: /
    Open-Source: open-source/
    Blog: blog/
    About: about/

# Profile
profile:
    location: BeiJing,  China
    github: xiaopeng163
    #stackoverflow:
        #title: yumemor
        #href: http://stackoverflow.com/users/5662132/yumemor
    #organization: test

#Widget
sidebar: true
navfixed: false

#WidgetText
excerpt_link: Continue Reading

github:
  popular_repos: ['www.pengxiao.me']
  contribute_repos: ['smartbgp/yabgp','smartbgp/yabmp', 'osrg/gobgp']

#Comments
#comments:
#   duoshuo_username: yumemor
comments:
        disqus_shortname: httpwwwpengxiaome
#Source Code
source_code: https://github.com/xiaopeng163/www.pengxiao.me
```

**Comment by akarineren** [comment]
首页的大标题应该是在 hexo 的 _config.yml 的 description 标签中配置 ，disqus 没生效的话 检查下 _widget/disqus-comments.ejs 里面的代码更换了吗？ 

项目最近没有更新，谢谢你的建议。

**Comment by xiaopeng163** [comment]
多谢

**Comment by fefr** [comment]
按照readme.md描述的把多说的注释掉后会运行命令hexo g会报错，加入disqus_shortname后虽然没报错但是评论界面还是多说的，disqus-comments.ejs里的代码更换过了。下面是我的配置:

``` yml
# Header
menu:
    Home: /
    Open-Source: open-source/
    Blog: blog/
    Guestbook: guestbook/

# Profile
profile:
    location: ZhongShan, China
    github: FEFR
    #stackoverflow: 
        #title: yumemor
        #href: http://stackoverflow.com/users/5662132/yumemor
    #organization: 组织/公司

#Widget
sidebar: true
navfixed: false

#WidgetText
excerpt_link: more

#Github(请务必配置github帐号)
#github:
        #popular_repos: ['ysale-sms','scude-answer','cordova-plugin-alipay']
        #contribute_repos: ['yumemor/fexo','yumemor/site']

#Comments
comments:
        #duoshuo_username: yumemor
    disqus_shortname: codekitchen-1

#Source Code
source_code: https://github.com/fefr/fefr.github.io
```
