### ISSUE TITLE
请教一个使用方面的问题

### ISSUE THREAD

**Issue by isnine** [yumemor/hexo-theme-primer#4]
你好，我使用时发现了一个报错
ERROR Process failed: layout/_widget/sidebar-categories
另外我发现好像主题代码高亮没办法用
我的博客地址是www.wxz.name

**Comment by isnine** [comment]
代码高亮已经解决了
发现在根目录的_config.yml文件中
```
highlight:
  enable: false
```
不能设置enable: true

sidebar-categories报错的原因还没想清楚

**Comment by akarineren** [comment]
关于代码高亮，
``` yaml
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
```
这样写是没有问题的，主题默使用的就是 highlight

关于 sidebar-categories ，你能够把报错的具体信息贴出来吗 ？ 这是你的文章分类
